[package]
name = "braided"
version = "0.2.0"
edition = "2024"
rust-version = "1.97"
description = "A library for defining and manipulating mathematical braids"
documentation = "https://docs.rs/braided"
readme = "README.md"
homepage = "https://github.com/jesse-a-l-hamer/braided"
repository = "https://github.com/jesse-a-l-hamer/braided"
license = "MIT"
keywords = ["braids", "knots", "topology"]
categories = ["mathematics"]
exclude = [
  ".github/",
]

[lib]
bench = false

[[bench]]
harness = false
name = "coalescence_by_band_height"

[[bench]]
harness = false
name = "coalescence_by_band_location"

[[bench]]
harness = false
name = "coalescence_by_band_number"

[[bench]]
harness = false
name = "multiplication_by_cancellation"

[[bench]]
harness = false
name = "multiplication_by_length"

[[bench]]
harness = false
name = "multiplication_by_type"

[dependencies]
thiserror = "2.0.19"
tracing = { version = "0.1.44", features = ["log"] }

[dev-dependencies]
criterion = { version = "0.8.2", features = ["html_reports"] }
googletest = "0.14.3"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
