[package]
name = "braided"
version = "0.1.0"
edition = "2024"
rust-version = "1.97"
description = "A library for defining and manipulating mathematical braids"
documentation = "https://docs.rs/braided"
readme = "README.md"
homepage = "https://github.com/jesse-a-l-hamer/braided"
repository = "https://github.com/jesse-a-l-hamer/braided"
license = "MIT"
keywords = ["braid theory", "braids", "knot theory", "knots", "topology"]
categories = ["mathematics"]

[dependencies]
thiserror = "2.0.19"

[dev-dependencies]
googletest = "0.14.3"
